#ifndef GUARD_CONSTANTS_BATTLE_INTRO_H
#define GUARD_CONSTANTS_BATTLE_INTRO_H

// vanilla: 2
#define BATTLE_INTRO_COMBATANT_SLIDE_IN_SPEED 3

#define BATTLE_INTRO_COMBATANT_SLIDE_OUT_SPEED_PLAYER 40
#define BATTLE_INTRO_COMBATANT_SLIDE_OUT_SPEED_ENEMY 35

#endif