#ifndef GUARD_MENU_SHORTSTRINGENTRY_CHARSETS
#define GUARD_MENU_SHORTSTRINGENTRY_CHARSETS

enum ShortStringEntryMenu_Charset {
   SHORTSTRINGENTRY_CHARSET_UPPER,
   SHORTSTRINGENTRY_CHARSET_LOWER,
   SHORTSTRINGENTRY_CHARSET_SYMBOL,
   SHORTSTRINGENTRY_CHARSET_ACCENT_UPPER,
   SHORTSTRINGENTRY_CHARSET_ACCENT_LOWER,
};

#include "lu/vui/custom-keyboard.h"
extern const struct VUICustomKeyboardCharset gShortStringEntryMenuCharsets[5];

#endif