#ifndef GUARD_MENU_SHORTSTRINGENTRY_GFX_TAGS
#define GUARD_MENU_SHORTSTRINGENTRY_GFX_TAGS

enum {
   SPRITE_GFX_TAG_CHARSET_BUTTONS = 0x9000,
   SPRITE_GFX_TAG_CHARSET_CURSORS,
   SPRITE_GFX_TAG_MENU_BTN_CURSOR,
   SPRITE_GFX_TAG_CURSOR_PARTICLE,
};

enum {
   SPRITE_PAL_TAG_CHARSET_BUTTON_NORMAL = 0x9000,
   SPRITE_PAL_TAG_CHARSET_BUTTON_ACTIVE,
   SPRITE_PAL_TAG_CURSORS,
   SPRITE_PAL_TAG_CUSTOM_ICON,
};

#endif