#ifndef GUARD_LU_FIELD_DEBUG_MENU_STRINGS_H
#define GUARD_LU_FIELD_DEBUG_MENU_STRINGS_H

#include "gba/types.h"

extern const u8 gText_lu_FieldDebugMenu_DisableTrainerLOS[];
extern const u8 gText_lu_FieldDebugMenu_DisableWildEncounters[];
extern const u8 gText_lu_FieldDebugMenu_EnableNationalDex[];
extern const u8 gText_lu_FieldDebugMenu_FastTravel[];
extern const u8 gText_lu_FieldDebugMenu_UseAnyBike[];
extern const u8 gText_lu_FieldDebugMenu_UseAnyFieldMove[];
extern const u8 gText_lu_FieldDebugMenu_UseAnyFishingRod[];
extern const u8 gText_lu_FieldDebugMenu_ViewPokedexEntry[];
extern const u8 gText_lu_FieldDebugMenu_SetTime[];
extern const u8 gText_lu_FieldDebugMenu_SetWeather[];
extern const u8 gText_lu_FieldDebugMenu_TestBattleTransition[];
extern const u8 gText_lu_FieldDebugMenu_WalkThroughWalls[];

extern const u8 gText_lu_FieldDebugMenu_UseAnyBike_Acro[];
extern const u8 gText_lu_FieldDebugMenu_UseAnyBike_Mach[];

extern const u8 gText_lu_FieldDebugMenu_UseAnyFishingRod_Old[];
extern const u8 gText_lu_FieldDebugMenu_UseAnyFishingRod_Good[];
extern const u8 gText_lu_FieldDebugMenu_UseAnyFishingRod_Super[];

extern const u8 gText_lu_FieldDebugMenu_SetWeather_SunnyCloudy[];
extern const u8 gText_lu_FieldDebugMenu_SetWeather_Sunny[];
extern const u8 gText_lu_FieldDebugMenu_SetWeather_Rain[];
extern const u8 gText_lu_FieldDebugMenu_SetWeather_Snow[];
extern const u8 gText_lu_FieldDebugMenu_SetWeather_Thunderstorm[];
extern const u8 gText_lu_FieldDebugMenu_SetWeather_Fog[];
extern const u8 gText_lu_FieldDebugMenu_SetWeather_Ashfall[];
extern const u8 gText_lu_FieldDebugMenu_SetWeather_Sandstorm[];
extern const u8 gText_lu_FieldDebugMenu_SetWeather_FogDiagonal[];
extern const u8 gText_lu_FieldDebugMenu_SetWeather_Underwater[];
extern const u8 gText_lu_FieldDebugMenu_SetWeather_Overcast[];
extern const u8 gText_lu_FieldDebugMenu_SetWeather_Drought[];
extern const u8 gText_lu_FieldDebugMenu_SetWeather_Downpour[];
extern const u8 gText_lu_FieldDebugMenu_SetWeather_UnderwaterBubbles[];
extern const u8 gText_lu_FieldDebugMenu_SetWeather_Abnormal[];
extern const u8 gText_lu_FieldDebugMenu_SetWeather_Route119Cycle[];
extern const u8 gText_lu_FieldDebugMenu_SetWeather_Route123Cycle[];

#define BATTLE_TRANSITION_MENU_ENTRY_STRING(name) \
   extern const u8 gText_lu_FieldDebugMenu_BattleTransition_##name [];
BATTLE_TRANSITION_MENU_ENTRY_STRING(BLUR)
BATTLE_TRANSITION_MENU_ENTRY_STRING(SWIRL)
BATTLE_TRANSITION_MENU_ENTRY_STRING(SHUFFLE)
BATTLE_TRANSITION_MENU_ENTRY_STRING(BIG_POKEBALL)
BATTLE_TRANSITION_MENU_ENTRY_STRING(POKEBALLS_TRAIL)
BATTLE_TRANSITION_MENU_ENTRY_STRING(CLOCKWISE_WIPE)
BATTLE_TRANSITION_MENU_ENTRY_STRING(RIPPLE)
BATTLE_TRANSITION_MENU_ENTRY_STRING(WAVE)
BATTLE_TRANSITION_MENU_ENTRY_STRING(SLICE)
BATTLE_TRANSITION_MENU_ENTRY_STRING(WHITE_BARS_FADE)
BATTLE_TRANSITION_MENU_ENTRY_STRING(GRID_SQUARES)
BATTLE_TRANSITION_MENU_ENTRY_STRING(ANGLED_WIPES)
BATTLE_TRANSITION_MENU_ENTRY_STRING(SIDNEY)
BATTLE_TRANSITION_MENU_ENTRY_STRING(PHOEBE)
BATTLE_TRANSITION_MENU_ENTRY_STRING(GLACIA)
BATTLE_TRANSITION_MENU_ENTRY_STRING(DRAKE)
BATTLE_TRANSITION_MENU_ENTRY_STRING(CHAMPION)
BATTLE_TRANSITION_MENU_ENTRY_STRING(AQUA)
BATTLE_TRANSITION_MENU_ENTRY_STRING(MAGMA)
BATTLE_TRANSITION_MENU_ENTRY_STRING(REGICE)
BATTLE_TRANSITION_MENU_ENTRY_STRING(REGISTEEL)
BATTLE_TRANSITION_MENU_ENTRY_STRING(REGIROCK)
BATTLE_TRANSITION_MENU_ENTRY_STRING(KYOGRE)
BATTLE_TRANSITION_MENU_ENTRY_STRING(GROUDON)
BATTLE_TRANSITION_MENU_ENTRY_STRING(RAYQUAZA)
BATTLE_TRANSITION_MENU_ENTRY_STRING(SHRED_SPLIT)
BATTLE_TRANSITION_MENU_ENTRY_STRING(BLACKHOLE)
BATTLE_TRANSITION_MENU_ENTRY_STRING(BLACKHOLE_PULSATE)
BATTLE_TRANSITION_MENU_ENTRY_STRING(RECTANGULAR_SPIRAL)
BATTLE_TRANSITION_MENU_ENTRY_STRING(FRONTIER_LOGO_WIGGLE)
BATTLE_TRANSITION_MENU_ENTRY_STRING(FRONTIER_LOGO_WAVE)
BATTLE_TRANSITION_MENU_ENTRY_STRING(FRONTIER_SQUARES)
BATTLE_TRANSITION_MENU_ENTRY_STRING(FRONTIER_SQUARES_SCROLL)
BATTLE_TRANSITION_MENU_ENTRY_STRING(FRONTIER_SQUARES_SPIRAL)
BATTLE_TRANSITION_MENU_ENTRY_STRING(FRONTIER_CIRCLES_MEET)
BATTLE_TRANSITION_MENU_ENTRY_STRING(FRONTIER_CIRCLES_CROSS)
BATTLE_TRANSITION_MENU_ENTRY_STRING(FRONTIER_CIRCLES_ASYMMETRIC_SPIRAL)
BATTLE_TRANSITION_MENU_ENTRY_STRING(FRONTIER_CIRCLES_SYMMETRIC_SPIRAL)
BATTLE_TRANSITION_MENU_ENTRY_STRING(FRONTIER_CIRCLES_MEET_IN_SEQ)
BATTLE_TRANSITION_MENU_ENTRY_STRING(FRONTIER_CIRCLES_CROSS_IN_SEQ)
BATTLE_TRANSITION_MENU_ENTRY_STRING(FRONTIER_CIRCLES_ASYMMETRIC_SPIRAL_IN_SEQ)
BATTLE_TRANSITION_MENU_ENTRY_STRING(FRONTIER_CIRCLES_SYMMETRIC_SPIRAL_IN_SEQ)
#undef BATTLE_TRANSITION_MENU_ENTRY_STRING

#endif