#ifndef GUARD_CGO_VALUETYPE_BATTLE_ITEM_USAGE
#define GUARD_CGO_VALUETYPE_BATTLE_ITEM_USAGE

#include "lu/c.h"
#include "lu/bitpack_options.h"
#include "gba/types.h"

enum LU_BP_MINMAX(0, 4) LU_BP_DEFAULT(0) CGO_BattleItemUsage WITH_UNDERLYING_TYPE(u8) {
   CGO_BATTLEITEMUSAGE_ENABLED = 0,
   CGO_BATTLEITEMUSAGE_NO_BACKLINE,
   CGO_BATTLEITEMUSAGE_NO_REVIVES,
   CGO_BATTLEITEMUSAGE_NO_BACKLINE_OR_REVIVES,
   CGO_BATTLEITEMUSAGE_DISABLED,
};

#endif