#ifndef GUARD_CGO_VALUETYPE_STARTER_POKEMON_GENDER
#define GUARD_CGO_VALUETYPE_STARTER_POKEMON_GENDER

#include "lu/c.h"
#include "lu/bitpack_options.h"
#include "gba/types.h"

enum LU_BP_MINMAX(0, 2) LU_BP_DEFAULT(0) CGO_StarterPokemonGender WITH_UNDERLYING_TYPE(u8) {
   CGO_STARTERPOKEMONGENDER_RANDOM = 0,
   CGO_STARTERPOKEMONGENDER_MALE,
   CGO_STARTERPOKEMONGENDER_FEMALE,
};

#endif